Set-Content -Path "main.js" -Value "const { app, BrowserWindow, ipcMain, dialog } = require('electron');"
Add-Content -Path "main.js" -Value "const path = require('path');"
Add-Content -Path "main.js" -Value "const fs = require('fs');"
Add-Content -Path "main.js" -Value "const Store = require('electron-store');"
Add-Content -Path "main.js" -Value "const store = new Store();"
Add-Content -Path "main.js" -Value "`nlet mainWindow;"
Add-Content -Path "main.js" -Value "`nfunction createWindow() {"
Add-Content -Path "main.js" -Value "  mainWindow = new BrowserWindow({"
Add-Content -Path "main.js" -Value "    width: 1200,"
Add-Content -Path "main.js" -Value "    height: 800,"
Add-Content -Path "main.js" -Value "    webPreferences: {"
Add-Content -Path "main.js" -Value "      nodeIntegration: true,"
Add-Content -Path "main.js" -Value "      contextIsolation: false"
Add-Content -Path "main.js" -Value "    }"
Add-Content -Path "main.js" -Value "  });"
Add-Content -Path "main.js" -Value "`n  mainWindow.loadFile('index.html');"
Add-Content -Path "main.js" -Value "`n  mainWindow.on('closed', function () {"
Add-Content -Path "main.js" -Value "    mainWindow = null;"
Add-Content -Path "main.js" -Value "  });"
Add-Content -Path "main.js" -Value "}"
Add-Content -Path "main.js" -Value "`napp.on('ready', createWindow);"
Add-Content -Path "main.js" -Value "`napp.on('window-all-closed', function () {"
Add-Content -Path "main.js" -Value "  if (process.platform !== 'darwin') app.quit();"
Add-Content -Path "main.js" -Value "});"
Add-Content -Path "main.js" -Value "`napp.on('activate', function () {"
Add-Content -Path "main.js" -Value "  if (mainWindow === null) createWindow();"
Add-Content -Path "main.js" -Value "});"
Add-Content -Path "main.js" -Value "`nipcMain.handle('select-file', async () => {"
Add-Content -Path "main.js" -Value "  const { canceled, filePaths } = await dialog.showOpenDialog({"
Add-Content -Path "main.js" -Value "    properties: ['openFile'],"
Add-Content -Path "main.js" -Value "    filters: ["
Add-Content -Path "main.js" -Value "      { name: 'Excel Files', extensions: ['xlsx', 'xls'] }"
Add-Content -Path "main.js" -Value "    ]"
Add-Content -Path "main.js" -Value "  });"
Add-Content -Path "main.js" -Value "  if (canceled) {"
Add-Content -Path "main.js" -Value "    return '';"
Add-Content -Path "main.js" -Value "  } else {"
Add-Content -Path "main.js" -Value "    return filePaths[0];"
Add-Content -Path "main.js" -Value "  }"
Add-Content -Path "main.js" -Value "});"
Add-Content -Path "main.js" -Value "`nipcMain.handle('get-app-data-path', () => {"
Add-Content -Path "main.js" -Value "  return app.getPath('userData');"
Add-Content -Path "main.js" -Value "});"
